server:
  port: 8082
spring:
  application:
    name: inventory-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ticket_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0

management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 表示100%采样，生产环境可适当调低，如0.1